spring:
  application:
    name: hr-user
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

server:
    port: ${PORT:0}

eureka:
    client:
        service-url:
          defaultZone: http://localhost:8761/eureka
